spring.application.name=AirbnbApp


#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb
#spring.datasource.url=jdbc:postgresql://postgres-spring.cpak0ygko7zz.ap-south-1.rds.amazonaws.com:5432/postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.username=postgres
spring.datasource.password=Lucky@01
#spring.datasource.username=root
#spring.datasource.password=LuckyBandhey01


server.servlet.context-path = /api/v1




jwt.secretKey=lksndkfls3423kjnw93r3fnnsdflksdfkju8ygf78ljng40f034tuhrg03894


frontend.url=http://localhost:8080

stripe.secret.key=sk_test_51MkOJlSI5PAqSMpFwMcZTyukE9lviKjcNUs1DJEeezZJY1yA4aRgWe6mldzsAfQq4eIkLVefps1rENKvEZpZT5fJ00IQJBbwyI
stripe.webhook.secret=whsec_6451df0d945d7e18acf040c8a96fbf3c4b5e564a25a1b4c26e2ffdfec96582f4







